version: '3'
services:
  xmrstak:
    container_name: xmrstak
    image: kristophjunge/xmrstak-cuda
    tty: true # docker-compose up hangs without
    environment:
      MINER_ID: ${GPUMINERNVIDIA_NAME}
      STARTUP_DELAY: ${XRN_STARTUP_DELAY}
      STRATUM: ${XRN_POOL_URL}
      WALLET: ${XRN_WALLET}
      PASSWORD: ${XRN_PASSWORD}
      CURRENCY: cryptonight_heavy
      THREADS: ${XRN_THREADS}
      BLOCKS: ${XRN_BLOCKS}
      BFACTOR: ${XRN_BFACTOR}
      BSLEEP: ${XRN_BSLEEP}
  prometheus_xmrstak:
    container_name: prometheus_xmrstak
    image: kristophjunge/prometheus-xmrstak
    restart: unless-stopped
    environment:
      TEST_MODE: 0
      API_URL: http://xmrstak:8080/api.json
      MINER_ID: ${GPUMINERNVIDIA_NAME}
    ports:
      - "9209:9209"
