version: '3'
services:
  ethminer:
    container_name: ethminer
    image: kristophjunge/ethminer-cuda
    restart: unless-stopped
    environment:
      STARTUP_DELAY: "${ETH_STARTUP_DELAY}"
      USERPASS: "${ETH_WALLET}.${GPUMINERNVIDIA_NAME}"
      STRATUM: "${ETH_POOL_URL}"
      FAILOVER_STRATUM: "${ETH_POOL_FAILOVER_URL}"
    ports:
      - "3333:3333"
  prometheus_ethminer:
    container_name: prometheus_ethminer
    image: kristophjunge/prometheus-ethminer
    restart: unless-stopped
    environment:
      TEST_MODE: 0
      API_URL: "ethminer:3333"
      MINER_ID: "${GPUMINERNVIDIA_NAME}"
    ports:
      - "9201:9201"
