version: '3'
services:
  gominer:
    container_name: gominer
    image: kristophjunge/decred-gominer-cuda
    restart: unless-stopped
    environment:
      STARTUP_DELAY: "${GOMINER_STARTUP_DELAY}"
      POOL: "${GOMINER_POOL}"
      POOLUSER: "${GOMINER_POOLUSER}.${GPUMINERNVIDIA_NAME}"
      POOLPASS: "${GOMINER_POOLPASS}"
      INTENSITY: "${GOMINER_INTENSITY}"
    volumes:
      - "/var/log/gpu-miner-nvidia/gominer:/var/log/gominer"
