version: '3'
services:
  ewbf:
    container_name: ewbf
    image: kristophjunge/ewbf
    restart: unless-stopped
    environment:
      STARTUP_DELAY: "${ZEC_STARTUP_DELAY}"
      SERVER: "${ZEC_POOL_HOST}"
      ADDRESS: "${ZEC_WALLET}"
      WORKER: "${GPUMINERNVIDIA_NAME}"
      PASS: "${ZEC_POOL_PASSWORD}"
      PORT: "${ZEC_POOL_PORT}"
  prometheus_ewbf:
    container_name: prometheus_ewbf
    image: kristophjunge/prometheus-ewbf
    restart: unless-stopped
    environment:
      TEST_MODE: 0
      API_URL: "http://ewbf:42000/getstat"
      MINER_ID: "${GPUMINERNVIDIA_NAME}"
    ports:
      - "9207:9207"
